### ISSUE TITLE
Checkout forma, modal dialog border

### ISSUE THREAD

**Issue by ipavicst** [nikoladadic/NH#6]
Kod neuspješne provjere kartice (nema obročnog plaćanja), border treba bit crven.

![image](https://cloud.githubusercontent.com/assets/14962583/19729516/8558fc1e-9b97-11e6-82d1-93c95b4436b6.png)

**Comment by ivantt1** [comment]
@ipavicst zašto si zatvoria ovaj?

**Comment by ipavicst** [comment]
Mislija sam da je riješen... Otvaram.

**Comment by mateozuro** [comment]
@ipavicst popravljano
